// Point the iOS app at a local Vite dev server instead of production, so UI
// changes can be checked in the simulator before they're deployed.
//
//   npm run ios:dev              # simulator -> http://localhost:5173
//   npm run ios:dev -- 192.168.1.20   # physical iPhone on the same Wi-Fi
//   npm run ios:prod             # back to https://courseforgeapp.ai
//
// Only the SYNCED copy (ios/App/App/capacitor.config.json) is rewritten. That
// file is gitignored and regenerated by every `cap sync`, so the tracked
// capacitor.config.json always stays on production and a dev URL can never be
// committed by accident.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const mode = process.argv[2];
const host = process.argv[3] || 'localhost';
const synced = 'ios/App/App/capacitor.config.json';

execSync('npx cap sync ios', { stdio: 'inherit' });   // resets the copy to production

if (mode === 'dev') {
  const cfg = JSON.parse(readFileSync(synced, 'utf8'));
  cfg.server = { ...cfg.server, url: `http://${host}:5173`, cleartext: true };
  writeFileSync(synced, JSON.stringify(cfg, null, 2) + '\n');
  console.log(`\niOS app now loads http://${host}:5173 — start Vite with: npm run dev -- --host`);
  console.log('Rebuild/run from Xcode (or `npx cap run ios`) to pick it up. `npm run ios:prod` to revert.');
} else {
  console.log('\niOS app loads production (https://courseforgeapp.ai).');
}
